version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # expose local port
    volumes:
      - .:/usr/src/app # mount local working directory for live reload
      - /usr/src/app/node_modules # mount node_modules for caching
